codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      server:
        target: auto
        threshold: 1%
        flags:
          - server
      client:
        target: auto
        threshold: 1%
        flags:
          - client
    patch:
      default:
        target: 80
        threshold: 1%
        base: auto

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  branches: [ ]
  show_carryforward_flags: false

flags:
  server:
    paths:
      - server/
    carryforward: true
  client:
    paths:
      - client/
    carryforward: true
