[libraries]
interop-common-jackson = "com.projectronin.interop:interop-common-jackson:3.4.0"
interop-common-http = "com.projectronin.interop:interop-common-http:3.4.0"
interop-aidbox = "com.projectronin.interop.publish:interop-aidbox:7.4.5"

interop-fhir = "com.projectronin.interop.fhir:interop-fhir:7.6.0"
interop-fhir-generators = "com.projectronin.interop.fhir:interop-fhir-generators:7.6.0"

mockk = "io.mockk:mockk:1.13.4"
spring-boot-parent = "org.springframework.boot:spring-boot-parent:2.7.8"
spring-bom = "org.springframework.boot:spring-boot-parent:2.7.8"

ktor-client-auth = "io.ktor:ktor-client-auth:2.2.4"
ktor-client-cio = "io.ktor:ktor-client-cio:2.2.4"
ktor-client-content-negotiation = "io.ktor:ktor-client-content-negotiation:2.2.4"
ktor-client-core = "io.ktor:ktor-client-core:2.2.4"
ktor-client-logging = "io.ktor:ktor-client-logging:2.2.4"
ktor-serialization-jackson = "io.ktor:ktor-serialization-jackson:2.2.4"
ronin-test-data-generator = "com.projectronin.test:ronin-test-data-generator:0.0.2"

ktorm-core = "org.ktorm:ktorm-core:3.6.0"
ktorm-support-mysql = "org.ktorm:ktorm-support-mysql:3.6.0"
liquibase-core = "org.liquibase:liquibase-core:4.20.0"
mysql-connector-java = "mysql:mysql-connector-java:8.0.32"

testcontainers-bom = "org.testcontainers:testcontainers-bom:1.17.6"

[bundles]
ktor = ["ktor-client-auth", "ktor-client-cio", "ktor-client-content-negotiation", "ktor-client-core", "ktor-client-logging", "ktor-serialization-jackson"]
data-generators = ["interop-fhir-generators", "ronin-test-data-generator"]
