[libraries]
interop-common-jackson = "com.projectronin.interop:interop-common-jackson:3.4.0"
interop-common-http = "com.projectronin.interop:interop-common-http:3.4.0"

ktorm-core = "org.ktorm:ktorm-core:3.6.0"
ktorm-support-mysql = "org.ktorm:ktorm-support-mysql:3.6.0"
liquibase-core = "org.liquibase:liquibase-core:4.20.0"
mysql-connector-java = "mysql:mysql-connector-java:8.0.32"
spring-boot-parent = "org.springframework.boot:spring-boot-parent:2.7.8"
spring-bom = "org.springframework.boot:spring-boot-parent:2.7.8"
testcontainers-bom = "org.testcontainers:testcontainers-bom:1.17.6"

[bundles]