plugins {
    id("com.projectronin.interop.gradle.spring-boot")
    id("com.projectronin.interop.gradle.integration")
    id("com.projectronin.interop.gradle.docker-integration")
}

dependencies {
    implementation(platform(libs.spring.boot.parent))
    implementation("org.springframework.boot:spring-boot-starter")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation(libs.interop.fhir)
    implementation(libs.interop.aidbox)
    implementation("org.springframework.boot:spring-boot-starter-jdbc")

    implementation(libs.ktorm.core)
    implementation(libs.ktorm.support.mysql)
    runtimeOnly(libs.liquibase.core)
    runtimeOnly(libs.mysql.connector.java)

    testImplementation(platform(libs.spring.boot.parent))
    testImplementation("org.springframework.boot:spring-boot-starter-test")

    testImplementation(libs.mockk)
    itImplementation(project)
    itImplementation(platform(libs.spring.boot.parent))
    itImplementation("org.springframework.boot:spring-boot-starter")
    itImplementation("org.springframework.boot:spring-boot-starter-web")
    itImplementation("org.springframework.boot:spring-boot-starter-actuator")
    itImplementation("org.springframework.boot:spring-boot-starter-test")
    itImplementation(platform(libs.testcontainers.bom))
    itImplementation("org.testcontainers:testcontainers")
    itImplementation(libs.interop.common.jackson)
    itImplementation(libs.bundles.ktor)
    itImplementation(libs.interop.fhir)
    itImplementation(libs.interop.aidbox)
    itImplementation(libs.bundles.data.generators)
    testImplementation(platform(libs.testcontainers.bom))
    testImplementation("org.testcontainers:mysql")
    testImplementation(libs.liquibase.core)
    testImplementation(libs.mysql.connector.java)
    itImplementation(libs.interop.common.jackson)
    itImplementation(libs.interop.common.http)
    itImplementation("ch.qos.logback:logback-classic:1.2.6")
    itImplementation("org.slf4j:slf4j-api:1.7.32")
}
