services:
  ehr-data-authority:
    restart: on-failure
    image: ehr-data-authority:local
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://springuser:ThePassword@ehr-data-authority-db:3306/dataauthority-db
    ports:
      - "8080:8080"
    depends_on:
      ehr-data-authority-db:
        condition: service_healthy

  ehr-data-authority-db:
    restart: always
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_DATABASE=dataauthority-db
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "springuser", "-pThePassword" ]
      timeout: 5s
      retries: 3