name: Build and Push Image
on:
  workflow_dispatch:
  workflow_run:
    workflows: [ EHR Data Authority Server Tests, Create Release ]
    types: [ completed ]
    branches: [ main ]
  
jobs:

  fetch-metadata:
    runs-on: self-hosted
    name: Fetch Project Version and other metadata
    steps:
      - name: Get version.
        id: get-version
        run: |
          VERSION=$(./gradlew currentVersion | awk '{ if(/Project version:/) { print $3; exit } }' | cut -d\- -f1)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      

  image-build-push:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: [ fetch-metadata ]
    name: Build and Push Image to Artifactory
    uses: projectronin/github/.github/workflows/image_push_nexus.yml@image_push_nexus/v2
    with:
      base-directory: ./server
      image-tag: ${{ github.sha }},${{ needs.fetch-metadata.outputs.version }},latest 
      build_boot_jar: true
    secrets:
      username: ${{ secrets.NEXUS_DOCKER_USERNAME }}
      password: ${{ secrets.NEXUS_DOCKER_PASSWORD }}


  argocd_dev:
    uses: projectronin/github/.github/workflows/argocd_deploy.yml@argocd_deploy/v1
    needs: 
      - fetch-metadata
      - image-build-push
    with:
      environment: dev
      image-tag: ${{ needs.fetch-metadata.outputs.version }}
    secrets:
      argocd-svc-automation: ${{ secrets.ARGOCD_SVC_AUTOMATION }}